source 'https://rubygems.org'

gem 'rails',          '~> 5.1.4'
gem 'activeresource'
gem 'sqlite3',        '1.3.9'
gem 'pry'
gem 'pry-nav'

gem 'daylight',       path: '../..'

group :test do
  gem 'rspec-rails', '~> 3.5.0'
  gem 'artifice',    '~> 0.6'
end
